# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fSV43zteSfna7esgEUJ4yQlnjc5Bcmax

# Обработка данных обучающего датасета

Импортируем библиотеки и загружаем данные
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import jupyter
import seaborn as sns
from sklearn.preprocessing import StandardScaler

data = pd.read_csv('train_data/loan_data.csv')
df = pd.DataFrame(data)

"""Умеренный дисбаланс

Заметим, что есть невозможные значения: возраст 144 года, стаж работы 125 лет
"""

df = df[df["person_age"] <= 100]
df = df[df["person_emp_exp"] <= df["person_age"] - 14]


"""Для всех числовых признаков посмотрим распредления"""

numeric_features = [
    "person_age",
    "person_income",
    "person_emp_exp",
    "loan_amnt",
    "loan_int_rate",
    "loan_percent_income",
    "cb_person_cred_hist_length",
    "credit_score"
]


"""Доход имеет сильную ассиметрию"""

df["person_income"] = np.log1p(
    df["person_income"]
)

"""Для категориальных признаков используем One-hot-encoding"""

categorical_features = [
    "person_gender",
    "person_education",
    "person_home_ownership",
    "loan_intent",
]

df = pd.get_dummies(
    df,
    columns=categorical_features,
    drop_first=True
)

df['previous_loan_defaults_on_file'] = df['previous_loan_defaults_on_file'].map({'Yes': 1, 'No': 0})

"""Возраст коррелирует со стажем работы слишком сильно - 0.95. Стаж работы более важен для того чтобы дать кредит, уберём возраст"""

df.drop(
    columns=[
        "person_age"
    ],
    inplace=True
)

"""Признаки с низкой корреляцией не удаляем, поскольку для ансамблевых моделей деревьев решений они могут сохранять прогностическую ценность

Масштабируем числовые признаки
"""

scaler = StandardScaler()

numeric_features.remove("person_age")
df[numeric_features] = scaler.fit_transform(
  df[numeric_features]
)

df.to_csv("new_loan_data.csv", index=False)
